### ISSUE TITLE
"seed" keyword not working and some issues in tests

### ISSUE THREAD

**Issue by laurentbristiel** [guykisel/robotframework-faker#17]
I am using robotframework-faker==2.0.4 with fake-factory==0.4.2
and don't succeed in having the "seed" keyword working.

I tried the tests provided in "tests" folder.
The test "Two Calls To Faker With Same Seed Should Give Same Results" fails.
I tried to use integers for the 2 calls:
```
    Two Calls To Faker With Same Seed Should Give Same Results
        FakerLibrary.Seed    ${5}
        ${name}=    FakerLibrary.Name
        Should Not Be Empty    ${name}
        FakerLibrary.Seed    ${5}
        ${name2}=    FakerLibrary.Name
        Should Not Be Empty    ${name2}
        Should Be Equal As Strings    ${name}    ${name2}
```
=> still failing

I tried another example by myself and fails also:
```
    Faker_seeding
        [Tags]  not_working
        FakerLibrary.Seed  ${5}
        ${name1} =  FakerLibrary.email
        FakerLibrary.Seed  ${5}
        ${name2} =  FakerLibrary.email
        Should Be Equal As Strings  ${name1}  ${name2}
```    
=> do I miss something or is there a regression? 

Note: in addition I have some other problems in the tests.
In total, 4 of them are failing (from Faker.robot)
For example "Can call Words with str integer argument fails" with "TypeError: range() integer end argument expected, got unicode."

**Comment by guykisel** [comment]
I think the problem here is that the tests were updated for robotframework-faker 2.0.5, which I haven't gotten around to releasing yet. Can you try running the tests against the latest commit in master? If that resolves your problem I'll do a new release to PyPI.

**Comment by laurentbristiel** [comment]
ah yes, you are right! it works with master. So I guess it would be a good idea to do a new release.

**Comment by guykisel** [comment]
@laurentbristiel I've released the latest changes at https://pypi.python.org/pypi/robotframework-faker/3.0.0 - please give it a try!

**Comment by laurentbristiel** [comment]
works perfectly! thanks!

**Comment by guykisel** [comment]
Great!
