### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by serhatbolsu** [guykisel/robotframework-faker#20]
Hello,

I believe imports are simple problem of this library not working in Python 3.x

Error I get: 
'FakerLibrary' failed: ImportError: No module named 'keywords'
Traceback (most recent call last):
  File "/Users/serhatbolsu/aliza/virtualenvs/venv_pointr/lib/python3.5/site-packages/FakerLibrary/__init__.py", line 2, in <module>
    from keywords import FakerKeywords

**Comment by guykisel** [comment]
Hey @serhatbolsu , thanks for the report! Are you interested in working on a fix for this?

**Comment by daveesposito** [comment]
@guykisel , I have a branch ready to push to fix this.  Can you please give me permission to push?  Here's the fix:

FakerLibrary.__init__.py update line 2 to use a relative import of the keywords module.  The line now reads:
`from .keywords import FakerKeywords`

**Comment by Bergil32** [comment]
I created a pull request with mentioned changes. Please check. 
#21

**Comment by guykisel** [comment]
fixed in #21

**Comment by guykisel** [comment]
i'll push out a new release today!

**Comment by guykisel** [comment]
@Bergil32 @daveesposito @serhatbolsu 4.2.0 is now up on PyPI and available for download with 3.x support. thanks all!
