### ISSUE TITLE
support faker 0.8.0

### ISSUE THREAD

**Issue by guykisel** [guykisel/robotframework-faker#23]
faker just released 0.8.0 which changes seed behavior.

**Comment by ek-akqa** [comment]
Hi any updates on this one?
It seems RobotFaker.Seed is not recognised now.

Here's what I see with Faker v2.0.2, Robot v3.1.2, and RobotFaker v4.2.0 respectively
```
No keyword with name 'FakerLibrary.Seed' found. Did you mean:
    FakerLibrary.Bs
    FakerLibrary.State
    FakerLibrary.Pyset
    FakerLibrary.Parse
```

The code I try to run is
```
*** Settings ***
Library  FakerLibrary  locale=de_DE

*** Keywords ***
Test Faker Seed
    ${t} =  Get Time  format=epoch
    FakerLibrary.Seed  ${t}
    ${email} =  FakerLibrary.Email

*** Test Cases ***
    Test Faker Seed
```

Or am I perhaps doing something wrong?

**Comment by guykisel** [comment]
ah, i have not had time to work on this :( i haven't actually used robot framework in several years so this project has not been a priority for me unfortunately. if someone opens a PR to fix this i will be happy to merge it :)
