### ISSUE TITLE
Hello, how should I fill in this parameter? Although it does not affect the use, but I want to know what the correct entry is, thank you.

### ISSUE THREAD

**Issue by clclclclclclcl** [guykisel/robotframework-faker#28]
![image](https://user-images.githubusercontent.com/49467409/59734513-4d326f00-9284-11e9-9ede-cee444baae89.png)
![image](https://user-images.githubusercontent.com/49467409/59734584-9387ce00-9284-11e9-8f38-4e22d5593bca.png)

**Comment by laurentbristiel** [comment]
@clclclclclclcl this looks rather a question for RIDE project. Please ask there if you did not find the answer yet: https://github.com/clclclclclclcl/RIDE
