### ISSUE TITLE
Library is not functional with  faker 3.0.0 version

### ISSUE THREAD

**Issue by Tanmay-Agrawal** [guykisel/robotframework-faker#30]
during a fresh install faker 3.0.0 gets installed. This is leading to  "Keyword Not Found" error. Though downgrading faker version to 2.0.5. This does not seems a legit solution.

**Comment by kpopovic** [comment]
Hello,
I also confirm that Faker==3.0.0 is an issue. I have done the downgrade to 2.0.5 and then robotframework-faker==4.2.0 works.

**Comment by tmatth** [comment]
> Hello,
> I also confirm that Faker==3.0.0 is an issue. I have done the downgrade to 2.0.5 and then robotframework-faker==4.2.0 works.

Same here.

**Comment by Tanmay-Agrawal** [comment]
I have found a solution, using command pip install  robotframework-faker -r requirements.txt, installs faker==0.7.8 which solves the problem

**Comment by guykisel** [comment]
hi all! apologies for the issue and for the delay in responding. i don't currently have the time to personally fix this, but if someone can fix it and submit a PR, i would be happy to merge it and release a new version.

**Comment by guykisel** [comment]
i've published 4.3.0 with @macejiko 's fix. thanks for your patience :)
