### ISSUE TITLE
FakerLibrary Keywords Not detected

### ISSUE THREAD

**Issue by mohamedyusuf** [guykisel/robotframework-faker#32]
__init__.py 
![image](https://user-images.githubusercontent.com/24860840/71802313-707d0a00-306e-11ea-831b-9ee5b97d40bc.png)

![image](https://user-images.githubusercontent.com/24860840/71802434-b5a13c00-306e-11ea-8de1-10eb656f4fd6.png)

Log:

------------------------------------------------------------------------------
 test library 'FakerLibrary' failed: ModuleNotFoundError: No module named 'faker.factory'
Traceback (most recent call last):
  File "c:\paython36\lib\site-packages\FakerLibrary\__init__.py", line 4, in <module>
    from .keywords import FakerKeywords
  File "c:\paython36\lib\site-packages\FakerLibrary\keywords.py", line 10, in <module>
    import faker.factory
PYTHONPATH:
  C:\Paython36\Scripts\robot.exe
  c:\paython36\python37.zip
  c:\paython36\DLLs
  c:\paython36\lib
  c:\paython36
  C:\Users\mshalakami\AppData\Roaming\Python\Python37\site-packages
  c:\paython36\lib\site-packages

**Comment by deevers** [comment]
this issue is with fakerlibrary dependency, we found downgrading the fake to 2.0.2 fixed the issue pip install -U Faker=='2.0.2'

**Comment by laurentbristiel** [comment]
This does not seem to happen with more recent versions of fakerlibrary and fake + no new comment from Mohamed, so I am closing the issue.
